version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/testingapp
    docker:
      # this is important to use proper image with browsers support
      - image: cimg/ruby:2.7.1-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: testingapp
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: testingapp_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: testingapp
      - image: redis:3.2.7
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore

        key: testingapp-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: testingapp-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format progress

      - type: store_test_results
        path: /tmp/test-results